### ISSUE TITLE
set up meeting for 22nd of Feb afternoon/morning 23rd with Trudell + Lawson

### ISSUE THREAD

**Issue by amymiller** [GliaX/meta#10]

**Comment by tareko** [comment]
Requirements first:
- [ ] Email Cheryl for follow-up
- [ ] Contact Mitch Barron at Trudel - either introduced or not
- [ ] Set time with Trudel
- [ ] Set time with Cheryl

**Comment by amymiller** [comment]
Ping! 
How are we doing here Tarek?
Meeting is set to be 7 or 8 business days away. I just want to make sure we will hit it or that we set it for the 27th (your next weekday off). 
Thanks amy

**Comment by amymiller** [comment]
PING #2!

**Comment by tareko** [comment]
Realistically, I think this has to be pushed back. I will email LHRI (Cheryl) later today.

**Comment by tareko** [comment]
Done
